### ISSUE TITLE
Alphabetical Order

### ISSUE THREAD

**Issue by 3bdulrahaman** [treyg/global-stream#1]
You have NO idea how long I’ve been looking for a website just like this. Please don’t EVER take it down, do anything you need to keep it running. I’ve seen similar websites but this one wins in every aspect, it’s simple, slick, and easy to use. I love this website so much and I wish I’ve found it long time ago. 
The only issue I noticed is that upon clicking on a streaming service to see which countries are supported by it, they’re not [always] in alphabetical order which can create some confusion.
Other than that, great job!!

**Comment by treyg** [comment]
@3bdulrahaman Thanks for the kind words! I got that updated so the countries should be in alphabetical order now. I fixed a couple bugs and made the modal a little more intuitive as well. You should now be able to close it by clicking anywhere outside of the modal body. Let me know if there's anything else you see!
