### ISSUE TITLE
Resu

### ISSUE THREAD

**Issue by karthikselvaraju** [treyg/global-stream#4]
Hi Bro,

Thank you so much for creating this site and i appreciate it so much! I recently noticed that the results are no longer loading. While you can search or a movie or TV show, when you click on it, the next page which loads no longer shows the streaming options. Is this something that could be fixed?

Thank you so much!

![Error](https://github.com/treyg/global-stream/assets/35722304/21c9ffb9-d71d-4d5e-a101-4bc27643d7ea)

**Comment by treyg** [comment]
@karthikselvaraju Thanks for bringing this up! It looks like there was an error is the string being used for the api call. It should be good to go now. Let me know if you're still seeing any issues!

**Comment by karthikselvaraju** [comment]
Thank you! its working perfectly now! :)

**Comment by miguelos6** [comment]
it failed a couple of days ago, then you fixed it, now it doesn't work again ...
